### ISSUE TITLE
The serialization of metatables by default breaks existing code

### ISSUE THREAD

**Issue by adriweb** [gvx/bitser#21]
Upon updating to the latest master, I've noticed that bitser tries to serialize metatables by default. This is probably all good when metatables are simple enough, like in the test cases, however when they contain things like functions, all hell breaks loose 😅
Would it be possible to disable this by default? So as to have a consistent default behaviour across versions?

**Comment by adriweb** [comment]
In case you agree, I've made a PR that would address that.

**Comment by gvx** [comment]
Honestly, because the previous behaviour of basically stripping metatables on serialization, it didn't occur to me that it was a valid use case, which would just require manual application of the metatable. And I expected people who want to serialize unserializable metatables to register those as resources.

I will review your PR!
