### ISSUE TITLE
Android and iOS use

### ISSUE THREAD

**Issue by tapir** [gvx/bitser#8]
Hello,
since JIT is disabled for both Android and iOS, is bitser still usable for these platforms?

Thanks

**Comment by gvx** [comment]
Bitser does not depend on JIT, and it seems like the ffi is not disabled, so it should still be usable on those platforms.

I would appreciate it if someone who has the means to do a quick test would report their findings in this thread, though, since I do not target those platforms myself.

If you're targeting those platforms yourself, I would suggest you try it out, @tapir, because I suspect it will work just fine. If it doesn't I'm afraid you'll have to use another serializing library, like [binser](/bakpakin/binser).

**Comment by tapir** [comment]
From what I understand withou JIT, FFI is very slow. I'll do your benchmark
in Android :+1

On 17 Mar 2017 00:37, "Robin Wellner" <notifications@github.com> wrote:

Bitser does not depend on JIT, and it seems like the ffi is not disabled,
so it should still be usable on those platforms.

I would appreciate it if someone who has the means to do a quick test would
report their findings in this thread, though, since I do not target those
platforms myself.

If you're targeting those platforms yourself, I would suggest you try it
out, @tapir <https://github.com/tapir>, because I suspect it will work just
fine. If it doesn't I'm afraid you'll have to use another serializing
library, like binser <http:///bakpakin/binser>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/gvx/bitser/issues/8#issuecomment-287198879>, or mute
the thread

**Comment by tapir** [comment]
Here are 2 tests (new and bigtable) http://imgur.com/a/ymRgb. intkeys test crashed the love android app.
Looks like bitser is slower then msgpack and binser on android. This is probably due to FFI being slow without JIT.

**Comment by tapir** [comment]
I can actualy replicate the same result on desktop with jit.off() in love.load
